baseURL = "https://docs.doxa.org"
languageCode = "en-us"
title = "Doxa Developer Documentation"
theme = "docsy"

[params]
  description = "Complete documentation for Doxa developers"
  github_repo = "https://github.com/doxa-fi/core"
  github_branch = "main"
  github_subdir = "docs"
  github_editlink = "https://github.com/doxa-fi/core/edit/main/docs/"
  ui.mermaid.enable = false

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -100
  [[menu.main]]
    identifier = "getting-started"
    name = "Getting Started"
    url = "/docs/getting-started/"
    weight = 10
  [[menu.main]]
    identifier = "core-concepts"
    name = "Core Concepts"
    url = "/docs/core-concepts/"
    weight = 20
  [[menu.main]]
    identifier = "protocol-integration"
    name = "Protocol Integration"
    url = "/docs/integration-guide/"
    weight = 25
  [[menu.main]]
    identifier = "pool-operations"
    name = "Pool Operations"
    url = "/docs/pool-operations/"
    parent = "protocol-integration"
    weight = 1
  [[menu.main]]
    identifier = "staking-integration"
    name = "Staking Integration" 
    url = "/docs/staking-integration/"
    parent = "protocol-integration"
    weight = 2
  [[menu.main]]
    identifier = "usdx-token-integration"
    name = "USDx Token Integration"
    url = "/docs/usdx-token-integration/"
    parent = "protocol-integration"
    weight = 3
  [[menu.main]]
    identifier = "liquidity-management"
    name = "Liquidity Management"
    url = "/docs/liquidity-management/"
    parent = "protocol-integration"
    weight = 4
  [[menu.main]]
    identifier = "fee-collection"
    name = "Fee Collection"
    url = "/docs/fee-collection/"
    parent = "protocol-integration"
    weight = 5
  [[menu.main]]
    identifier = "transaction-monitoring"
    name = "Transaction Monitoring"
    url = "/docs/transaction-monitoring/"
    parent = "protocol-integration"
    weight = 6
  [[menu.main]]
    identifier = "statistics-data"
    name = "Statistics & Data"
    url = "/docs/statistics-data/"
    parent = "protocol-integration"
    weight = 7
  [[menu.main]]
    identifier = "api-reference"
    name = "API Reference"
    url = "/docs/api-reference/"
    weight = 30
  [[menu.main]]
    identifier = "guides"
    name = "Guides"
    url = "/docs/guides/"
    weight = 40
  [[menu.main]]
    identifier = "troubleshooting"
    name = "Troubleshooting"
    url = "/docs/troubleshooting/"
    weight = 50

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
